"""update changes to users

Revision ID: 0e0f333eca56
Revises: afada44c61f3
Create Date: 2020-05-04 12:15:47.967674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0f333eca56'
down_revision = 'afada44c61f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
